name: Deploy development environment

on:
  workflow_dispatch:

jobs:
  deployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Deploy dev
        run: |
          echo "Dev environment deployed... running gates"
      - name: Get latest release tag
        id: tag_name
        run: |
          tagname=$(gh api repos/SullyDevSquad/repository-dispatch-poc/releases/latest | jq .tag_name)
          echo "$tagName is this"
          echo "tagname=$tagname" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Make repo dispatch call
        id: repo-dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: kick-gates
          token: ${{ secrets.PAT }}
          client-payload: '{"version": "${{ steps.tag_name.outputs.tagname }}"}'
          
          
