name: Deploy development environment

on:
  workflow_dispatch:

jobs:
  deployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev
        run: |
          echo "Dev environment deployed... running gates"
      - name: Make repo dispatch call
        id: repo-dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: kick-gates
          token: ${{ secrets.PAT }} 
          
