# This is a basic workflow to help you get started with Actions

name: Kickoff QA Deploy

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [kickoff-qa-deploy]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  parseResultsIntoGitHubSummary:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          # get test pass percent and security results
          test_pass_percent=${{ github.event.client_payload.test_pass_percent }}
          security_checks_passed=${{ github.event.client_payload.security_checks_passed }}

          # write to a summary markdown table
          summary_table="| Test Pass Percent | Security Checks Passed |\n| --- | --- |\n| $test_pass_percent | $security_checks_passed |"

          # append to github step summary
          echo "## Gating result" >> $GITHUB_STEP_SUMMARY
          echo "### Test Pass Percent: $test_pass_percent" >> $GITHUB_STEP_SUMMARY
          echo "### Security Checks Passed: $security_checks_passed" >> $GITHUB_STEP_SUMMARY

  deployQA:
    runs-on: ubuntu-latest
    environment: QA
    needs: [parseResultsIntoGitHubSummary]
    steps:
      - name: Deploy to QA
        run: |
          echo "Deploying to QA..."

